services:
  - type: web
    name: job-matcher-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
  
  - type: static
    name: job-matcher-frontend
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /api/*
        destination: https://job-matcher-api.onrender.com/*